# Generated by Django 4.2 on 2024-12-10 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Carts", new_name="Cart",),
        migrations.RenameModel(old_name="OrderItems", new_name="OrderItem",),
        migrations.RenameModel(old_name="Variants", new_name="Variant",),
        migrations.AlterModelOptions(
            name="gallery", options={"verbose_name_plural": "Gallery"},
        ),
    ]
